substitutions:
  log_level: DEBUG
  sub_baud_rate: "115200"

external_components:
  - source:
      type: git
      url: "https://github.com/Marsupilami23/esphome"
      ref: dev
      refresh: alwasy
    components:
        [ "http_request" ]
      
globals:
  - id: burn_category
    type: int
    restore_value: true
    initial_value: "0"
 
# Enable logging bia network and disable serial port
logger:
  level: "${log_level}"
  baud_rate: "${sub_baud_rate}"

http_request:
  id: burn_check_request
  verify_ssl: false

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  # Diagnostic sensor for connection
  - platform: status
    name: "API Status"
    id: sensor_status
    disabled_by_default: true

text_sensor:
  - platform: template
    id: burn_status
    name: "Burn Status"
    icon: mdi:fire
    
sensor:
  - platform: template
    id: burn_status_sensor
    name: "Burn Status Category"
    icon: "mdi:fire"
          
# Provide a pre-built button for restart the device
button:
  - platform: restart
    name: "Reboot Device"
    id: button_restart
    icon: mdi:power-cycle
    entity_category: "diagnostic"
