globals:
  - id: burn_category
    type: int
    restore_value: true
    initial_value: "0"
  - id: global_burn_category
    type: globals::GlobalsComponent<int>*
    initial_value: "App.get_component<globals::GlobalsComponent<int>>(id(burn_category))"
  - id: global_burn_status
    type: text_sensor::TextSensor*
    initial_value: "App.get_component<text_sensor::TextSensor>(id(burn_status))"
  - id: global_burn_status_sensor
    type: sensor:Sensor*
    initial_value: "App.get_component<sensor::Sensor>(id(burn_status_sensor))"

logger:

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  # Diagnostic sensor for connection
  - platform: status
    name: "API Status"
    id: sensor_status
    disabled_by_default: true

text_sensor:
  - platform: template
    id: burn_status
    name: "Burn Status"
    icon: mdi:fire
    
sensor:
  - platform: template
    id: burn_status_sensor
    name: "Burn Status Category"
    icon: "mdi:fire"
          
# Provide a pre-built button for restart the device
button:
  - platform: restart
    name: "Reboot Device"
    id: button_restart
    icon: mdi:power-cycle
    entity_category: "diagnostic"
