substitutions:
  log_level: DEBUG
  sub_baud_rate: "115200"

# Enable logging bia network and disable serial port
logger:
  level: "${log_level}"
  baud_rate: "${sub_baud_rate}"

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  # Diagnostic sensor for connection
  - platform: status
    name: "API Status"
    id: sensor_status
    disabled_by_default: true

# Provide a pre-built button for restart the device
button:
  - platform: restart
    name: "Reboot Device"
    id: button_restart
    icon: mdi:power-cycle
    entity_category: "diagnostic"
