# https://esphome.io/components/esphome.html
esphome:
  name: "${sub_name}"
  friendly_name: "${sub_friendly_name}"
  name_add_mac_suffix: false
  version: "2024.12.2"
  includes: 
    - burn_functions/burn_functions.h
    - burn_functions/burn_functions.cpp
  libraries:
    - ArduinoJson
  on_boot:
    priority: -100
    then:
      - lambda: |-
          global_burn_category = id(burn_category);
          global_burn_status = id(burn_status);
          global_burn_status_sensor = id(burn_status_sensor);
          fetchAndParseBurnData();
