# https://esphome.io/components/esphome.html
esphome:
  name: "${sub_name}"
  friendly_name: "${sub_friendly_name}"
  name_add_mac_suffix: false
  min_version: "2024.11.0"
  includes: 
    - github://Marsupilami23/myesphometemplates/tree/dev/components/burn_forecast/burn_forecast.h
    - github://Marsupilami23/myesphometemplates/tree/dev/components/burn_forecast/burn_forecast.cpp
  libraries:
    - ArduinoJson
  on_boot:
    priority: -100
    then:
      - lambda: |-
           // Initial fetch on boot
           fetchAndParseBurnData();
