# https://esphome.io/components/esphome.html
esphome:
  name: "${sub_name}"
  friendly_name: "${sub_friendly_name}"
  name_add_mac_suffix: false
  min_version: "2024.11.0"
  includes: 
    - https://github.com/Marsupilami23/burn_functions/burn_forecast.h?ref=main
    - https://github.com/Marsupilami23/burn_forecast/burn_forecast.cpp?ref=main
  libraries:
    - ArduinoJson
  on_boot:
    priority: -100
    then:
      - lambda: |-
           // Initial fetch on boot
           fetchAndParseBurnData();
