# https://esphome.io/components/esphome.html
esphome:
  name: "${sub_name}"
  friendly_name: "${sub_friendly_name}"
  name_add_mac_suffix: false
  includes: 
    - burn_functions/burn_functions.h
    - burn_functions/burn_functions.cpp
  libraries:
    - ArduinoJson
  on_boot:
    priority: -100
    then:
      - lambda: |-
          global_burn_category = App.get_component<esphome::globals::GlobalsComponent<int>>(id(burn_category));
          global_burn_status = App.get_component<esphome::text_sensor::TextSensor>(id(burn_status));
          global_burn_status_sensor = App.get_component<esphome:sensor:Sensor>(id(burn_status_sensor));
      - lambda: |-
           // Initial fetch on boot
           fetchAndParseBurnData();
