# https://esphome.io/components/esphome.html
esphome:
  name: "${sub_name}"
  friendly_name: "${sub_friendly_name}"
  name_add_mac_suffix: false
  min_version: "2024.12.2"
  on_boot:
    priority: -100
    then:
      - lambda: |-
            #include <HTTPClient.h>
            #include <ArduinoJson.h>
            const char serverAddress[] = "sonomatech-production.s3.amazonaws.com";
            String path = "/sacramento/airquality_org/cbyb-widget/burncheckForecast.txt";
            int port = 80;
            HTTPClient client;
            client.begin(serverAddress, port, path);
            String responseBody = client.getStream();
            
            
            // Remove "burncheckForecastCallback(" and ")" from the response
            String cleaned_body = responseBody;
            cleaned_body.remove(0, strlen("burncheckForecastCallback("));
            cleaned_body.remove(cleaned_body.length() - 1);
            
            JsonDocument doc;
            
            DeserializationError error = deserializeJson(doc, clean_body);
            
            int burnCategory = doc["burn_forecast"]["today"]["category"];
