# https://esphome.io/components/esphome.html
esphome:
  name: "${sub_name}"
  friendly_name: "${sub_friendly_name}"
  name_add_mac_suffix: false
  min_version: "2024.11.0"
  on_boot:
    priority: -100
    then:


external_components:
  - source:
      type: git
      url: https://github.com/libretiny-eu/libretiny-esphome
      ref: dev
    components: [ "http_request", "json" ]
    refresh: always
