substitutions:
  # WIFI Substitutions
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password
  sub_ota_num_attempts: "15"

external_components:
  - source:
      type: git
      url: https://github.com/Marsupilami23/myesphometemplates
      ref: dev
    components:
      [ "my_web_server" ]
      
sensor:
  - platform: wifi_signal
    name: "RSSI"
    id: sensor_rssi
    update_interval: 60s
    entity_category: "diagnostic"

api:

# Enable OTA
ota:
  - platform: esphome
    id: my_ota
    password: "${ota_password}"
    on_error:
      then:
        - button.press: button_restart
  
# Enable WIFI and AP for capitve portal
wifi:
  id: wifi_brg95758
  fast_connect: false
  power_save_mode: none

  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  ap:
    ssid: "${sub_name}-setup"
    password: "${wifi_password}"

libretiny_web_server:
  id: burn_status_web_server
  port: 80

captive_portal:
