# ESPHome firmware template for CREE C/W Bulb
# 
# initial code taken from
# https://github.com/esphome/issues/issues/3487
# Analysis from:
# https://github.com/arendst/Tasmota/issues/6914

substitutions:
  api_key: "Change me"
  # Required import substitutions
  device_site: "home"
  device_location_code: "changeme"
  device_location_name: "Change Me"
  device_type_code: "changeme"
  device_type_name: "Change Me"
  device_number: "000"
  device_ip: "0.0.0.0"

  disable_entities: "true"
  disable_webserver: "false"
  
  sub_on_turn_on: script_do_nothing
  sub_on_turn_off: script_do_nothing

  sub_cw_pin: GPIO26
  sub_ww_pin: GPIO24
  sub_adc_pin: GPIO23
  
  sub_warm_white_temp: 2800 Kelvin
  sub_cold_white_temp: 6600 Kelvin

  sub_cw_freq: 400hz
  sub_ww_freq: 400hz

  sub_reboot_req: '9'
  sub_ota_num_attempts: '15'

  sub_max_power: '0.8'
  sub_default_transition_length: 250ms
  sub_api_reboot_timeout: 0s
  light_restore_mode: RESTORE_DEFAULT_ON

    # Project Substitutions (not intended for user substitutions
  device_model: "St19"
  device_make: "CREE"
  package_version: "2024.11.18"
  package_url: "github://Marsupilami23/myesphometemplates/cree-st19-bulb.yaml@main"

# Allow importing this package
dashboard_import:
  package_import_url: "${package_url}"
  import_full_config: false

# https://esphome.io/components/external_components.html
external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
    components: [ wifi ]
    refresh: always

# Import packages:
packages:
  standard_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - cree-st19-bulbs/standard/project.yaml
      - cree-st19-bulbs/standard/diagnostics.yaml
      - cree-st19-bulbs/standard/wifi.yaml
  cree_st19_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - cree-st19-bulbs/board.yaml
      - cree-st19-bulbs/current-sensor.yaml
      - cree-st19-bulbs/pwm-outputs.yaml
      - cree-st19-bulbs/scripts.yaml
      - cree-st19-bulbs/virtual_buttons.yaml

light:
  - platform: monochromatic
    name: "Cold White"
    id: cw_light
    output: pwm_cw_output

  - platform: monochromatic
    name: "Warm White"
    id: ww_light
    output: pwm_ww_output

  - platform: status_led
    name: "Switch state"
    pin: "${sub_cw_pin}"
