# ESPHome firmware template for CREE C/W Bulb
# 
# initial code taken from
# https://github.com/esphome/issues/issues/3487
# Analysis from:
# https://github.com/arendst/Tasmota/issues/6914

substitutions:
  name: CHNAGE ME
  friendly_name: CHANGE ME
  api_key: "CHANCE ME"
  disable_entities: "true"
  disable_webserver: "false"
  wifi_ap_timeout: 2min
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password
  project_name: CREE.CWWW
  project_ver_num: "1.0"
  project_ver_let: a

  sub_on_turn_on: script_do_nothing
  sub_on_turn_off: script_do_nothing

  sub_cw_pin: GPIO26
  sub_ww_pin: GPIO24

  sub_warm_white_temp: 2800 Kelvin
  sub_cold_white_temp: 6600 Kelvin

  sub_cw_freq: 400hz
  sub_ww_freq: 400hz

  sub_reboot_req: '9'
  sub_ota_num_attempts: '15'

  sub_max_power: '0.8'
  sub_default_transition_length: 250ms
  sub_api_reboot_timeout: 0s
  light_restore_mode: RESTORE_DEFAULT_ON

