substitutions:
  sub_name: "changeme"
  sub_friendly_name: "Change Me"
  sub_ap_timeout: 15s

  sub_neopixelbus_pin: GPIO01
  sub_user_pin: GPIO21
  sub_wake_pin: GPIO08
  
  disable_entities: "true"

# Import packages:
packages:
  standard_packages:
    url: https://github.com/Marsupilami23/myesphometemplates
    ref: dev
    refresh: always
    files:
      - esp32s3/standard/project.yaml
      - esp32s3/standard/diagnostics.yaml
      - esp32s3/standard/wifi.yaml
  dogain_rgbww_packages:
    url: https://github.com/Marsupilami23/myesphometemplates
    ref: dev
    refresh: always
    files:
      - esp32s3/board.yaml
      - esp32s3/pwm-outputs.yaml
      - esp32s3/scripts.yaml
