substitutions:
  sub_name: esp32-tester
  sub_friendly_name: "ESP32S3 Testing Chip"
  sub_ap_timeout: 15s

  disable_entities: "true"
  package_url: "github://Marsupilami23/myesphometemplates/esp32s3.yaml@main"

# Import packages:
packages:
  standard_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - esp32/standard/project.yaml
      - esp32/standard/diagnostics.yaml
      - esp32/standard/wifi.yaml
  dogain_rgbww_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - esp32/board.yaml
