substitutions:
  api_key: "Change me"
  # Required import substitutions
  device_site: "home"
  device_location_code: "changeme"
  device_location_name: "Change Me"
  device_type_code: "plg"
  device_type_name: "Smart Plug"
  device_ip: "0.0.0.0"

  # https://esphome.io/components/switch/gpio.html?highlight=restore_mode
  sub_restore_mode: RESTORE_DEFAULT_ON  # overwrite to change boot up behavior of relay

  disable_entities:  "true"     # set to "false" to have all entities show up in Home Assistant automatically
  disable_webserver: "false"    # set to "true" to disable the webserver listening on port 80.

  # substitutions for button actions.  on_press and on_release implement a timer scheme with configurable delay.
  # on_hold_30s re-enables the AP and captive portal for the precompiled update binary.
  # any length of hold can be implemented with just on_press and on_release using the following directions.  This
  # is basically how this yaml file works.
  #   * have a delay for the desired hold in the on_press script
  #   * stop the on_press script in the on_release script
  #   * place actions in the on_press script after the delay to perform them while still holding the button
  #   * place actions in the on_release script, with the condition that the on_press script is not running, to
  #     perform them on release of the button.
  sub_on_press:         script_do_nothing  # executes right when button is initially pressed
  sub_on_release:       script_do_nothing  # executes right when button is released
  sub_on_hold_30s:      script_force_ap    # executes right when button has been held for 5s, while button is still being held

  sub_on_turn_on:       script_do_nothing
  sub_on_turn_off:      script_do_nothing

  # an extra script that, if running, will stop the relay from toggling on button release.
  # used to not toggle when WiFi AP is re-enabled on update bin file.
  sub_toggle_check: script_force_ap

  # made this a substitution so that the update bin file and yaml compiled versions can have different defaults
  default_button_config: "Toggle on Press"

  # substitutions for power monitoring calibration.  Allows end users to change calibration in their yaml and still
  # incorporate this file as a package to get all the updates we release.
  current_resistor_val: "0.001"
  voltage_divider_val:  "2001"
  sub_hlw_model:         BL0937
  power_cal_val1_in:    "0.0"
  power_cal_val1_out:   "0.0"
  power_cal_val2_in:    "879.4"
  power_cal_val2_out:   "750"
  current_cal_val1_in:  "0.0"
  current_cal_val1_out: "0.0"
  current_cal_val2_in:  "6.8"
  current_cal_val2_out: "3.5"
  voltage_cal_val1_in:  "0.0"
  voltage_cal_val1_out: "0.0"
  voltage_cal_val2_in:  "132.7"
  voltage_cal_val2_out: "119.1"

  sub_default_scale_power: "87"
  sub_default_scale_current: "162"
  sub_default_scale_voltage: "85"

  # set default power monitoring update interval in yaml.
  # this will only be effective as long as the select entity is set to "YAML Configured"
  sub_update_interval: 10s
  sub_pm_initial_option: YAML Configured ($sub_update_interval)

  sub_hlw_timeout: 3s

  # for early sensor publishing
  sub_early_publish_percent:           "25"
  sub_early_publish_percent_min_power: "0.5"
  sub_early_publish_absolute:          "16.68" # for PLF10, 1w is approximately 5.56.  16.68 is approximately 3w.

  # GPIO definitions
  sub_pm_sel_pin:   GPIO12
  sub_pm_cf_pin:    GPIO5
  sub_pm_cf1_pin:   GPIO14
  sub_button_pin:   GPIO13
  sub_blue_led_pin: GPIO2
  sub_red_led_pin:  GPIO0
  sub_relay_pin:    GPIO4

  # debounce specifications
  sub_default_debounce: "20"
  sub_min_debounce:     "10"

  sub_reboot_req: '9'
  sub_ota_num_attempts: '15'
  sub_api_reboot_timeout: 0s

 # Project Substitutions (not intended for user substitutions)
  package_url: "github://Marsupilami23/myesphometemplates/kauf-plf12-plug.yaml@main"

# Allow importing this package
#dashboard_import:
#  package_import_url: "${package_url}"
#  import_full_config: false

# https://esphome.io/components/external_components.html
external_components:
  - source:
      type: git
      url: https://github.com/KaufHA/common
      ref: v2024.11.20
    refresh: always

# Import packages:
packages:
  standard_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - kauf-plf12-plug/standard/project.yaml
      - kauf-plf12-plug/standard/diagnostics.yaml
      - kauf-plf12-plug/standard/wifi.yaml
  cree_st19_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - kauf-plf12-plug/board.yaml
      - kauf-plf12-plug/scripts.yaml
      - kauf-plf12-plug/pwm-outputs.yaml
      - kauf-plf12-plug/buttons.yaml
      - kauf-plf12-plug/sensors.yaml

# https://esphome.io/components/binary_sensor/index.html
binary_sensor:
    # button input toggles relay and thereby power led
    # https://esphome.io/components/binary_sensor/gpio.html
  - platform: gpio
    id: button_in
    name: $device_name Button
    pin:
      number: $sub_button_pin
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - lambda: |-
          // store time of press and clear duration sensor
          id(global_press_time) = millis();
          id(sensor_press_duration).publish_state(0);

          // toggle if configured for toggle on press
          if (id(select_button).state == "Toggle on Press") {
            id(relay).toggle(); }
      - script.execute: $sub_on_press
      - script.execute: script_30s_timer
    on_release:
      - lambda: |-
          // set duration sensor
          id(sensor_press_duration).publish_state(millis() - id(global_press_time) + id(number_debounce).state);

          // toggle if configured on release and toggle check script is not running.
          if (  (id(select_button).state == "Toggle on Release") && !id($sub_toggle_check).is_running() ) {
            id(relay).toggle();
          }
      - script.execute: $sub_on_release
      - script.stop: script_30s_timer
    filters:
      - delayed_on: !lambda return id(number_debounce).state;

    # indicates whether plugged-in device is running based on configurable threshold.
    # https://esphome.io/components/binary_sensor/template.html
  - platform: template
    id: in_use
    name: $device_name Device In Use

switch:
  # relay output
  # https://esphome.io/components/switch/gpio.html
  - platform: gpio
    id: relay
    name: $device_name
    pin: $sub_relay_pin
    entity_category: ''
    forced_hash: 41191675
    forced_addr: 2
    global_addr: global_forced_addr
    restore_mode: $sub_restore_mode
    on_turn_on:
        - script.execute: script_set_power_leds
        - script.execute: $sub_on_turn_on
    on_turn_off:
        - script.execute: script_set_power_leds
        - script.execute: $sub_on_turn_off

    # https://esphome.io/components/switch/template.html
  - platform: template
    id: switch_no_hass
    name: $device_name No HASS
    optimistic: true
    entity_category: config
    disabled_by_default: $disable_entities
    icon: mdi:toggle-switch-off-outline
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - lambda: |-
          id(kauf_api).set_reboot_timeout(0);  // 0 disables auto rebooting and also new status led blinking.  doesn't stop current status led blinking
          id(kauf_api).status_clear_warning(); // stops current status led blinking, timeout 0 keeps it from restarting
      - script.execute: script_save_changes
    on_turn_off:
      - lambda: id(kauf_api).set_reboot_timeout(900000);
      - script.execute: script_save_changes
    forced_hash: 657159011
    forced_addr: 42
    global_addr: global_forced_addr

  - platform: template
    id: blue_led
    name: $device_name Blue LED
    optimistic: true
    entity_category: config
    disabled_by_default: $disable_entities
    icon: mdi:led-outline
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(blue_led_pwm).set_level(id(blue_led_brightness).state/100);
    on_turn_off:
      - lambda: id(blue_led_pwm).set_level(0.0);
    forced_hash: 1329407616
    forced_addr: 44
    global_addr: global_forced_addr

  - platform: template
    id: red_led
    name: $device_name Red LED
    optimistic: true
    entity_category: config
    disabled_by_default: $disable_entities
    icon: mdi:led-outline
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(red_led_pwm).set_level(id(red_led_brightness).state/100);
    on_turn_off:
      - lambda: id(red_led_pwm).set_level(0.0);
    forced_hash: 261191305
    forced_addr: 48
    global_addr: global_forced_addr

  - platform: template
    id: switch_early_publish
    name: $device_name Early Publish
    optimistic: true
    entity_category: config
    disabled_by_default: $disable_entities
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(hlw_main).enable_early_publish();
    on_turn_off:
      - lambda: id(hlw_main).disable_early_publish();
    forced_hash: 1334841796
    forced_addr: 62
    global_addr: global_forced_addr

# https://esphome.io/components/sensor/index.html
sensor:   # Power monitoring sensors output to Home Assistant

    # https://esphome.io/components/sensor/hlw8012.html
  - platform: kauf_hlw8012
    id: hlw_main
    sel_pin:
      number: $sub_pm_sel_pin
      inverted: True
    cf_pin: $sub_pm_cf_pin
    cf1_pin: $sub_pm_cf1_pin
    current_resistor: $current_resistor_val
    voltage_divider: $voltage_divider_val

    update_interval: $sub_update_interval

    timeout:                         $sub_hlw_timeout
    early_publish_percent:           $sub_early_publish_percent
    early_publish_percent_min_power: $sub_early_publish_percent_min_power
    early_publish_absolute:          $sub_early_publish_absolute

    model: $sub_hlw_model

    power:
      name: $device_name Power
      unit_of_measurement: W
      id: wattage
      filters:
        - calibrate_linear:
            - $power_cal_val1_in -> $power_cal_val1_out
            - $power_cal_val2_in -> $power_cal_val2_out
        - lambda: |-
              // filter out extremely large values that are incorrect
              float return_val = x * id(scale_power).state/100.0f;
              if ( return_val > 5000.0f) return {};
              else return return_val;
      on_value:   # set or clear in_use template binary sensor depending on whether power usage is over threshold
        - lambda: id(in_use).publish_state(x >= id(threshold).state);

    current:
      name: $device_name Current
      unit_of_measurement: A
      id: current
      filters:
        - calibrate_linear:
            - $current_cal_val1_in -> $current_cal_val1_out
            - $current_cal_val2_in -> $current_cal_val2_out
        - lambda: return x * id(scale_current).state/100.0f;

    voltage:
      name: $device_name Voltage
      unit_of_measurement: V
      id: voltage
      filters:
        - calibrate_linear:
            - $voltage_cal_val1_in -> $voltage_cal_val1_out
            - $voltage_cal_val2_in -> $voltage_cal_val2_out
        - lambda: return x * id(scale_voltage).state/100.0f;

    # Reports the total Power so-far each day, resets at midnight
    # https://esphome.io/components/sensor/total_daily_energy.html
  - platform: total_daily_energy
    name: $device_name Total Daily Energy
    power_id: wattage
    filters:
        - multiply: 0.001  ## convert Wh to kWh
    unit_of_measurement: kWh
    forced_hash: 1903527169
    forced_addr: 6
    global_addr: global_forced_addr

    # https://esphome.io/components/sensor/uptime.html
  - platform: uptime
    name: $device_name Uptime
    update_interval: 60s
    entity_category: diagnostic
    disabled_by_default: $disable_entities

    # https://esphome.io/components/sensor/template.html
  - platform: template
    name: $device_name Button Press Duration
    id: sensor_press_duration
    entity_category: diagnostic
    disabled_by_default: $disable_entities
    unit_of_measurement: ms
    icon: mdi:timer-outline

    # https://esphome.io/components/number/index.html
# https://esphome.io/components/number/template.html
number:      # used as a threshold for whether the plugged-in devices is running.
  - platform: template
    name: $device_name Use Threshold
    min_value: 1
    max_value: 100
    step: 1
    initial_value: 3
    id: threshold
    entity_category: config
    optimistic: true
    restore_value: true
    unit_of_measurement: Watt(s)
    mode: box
    disabled_by_default: $disable_entities
    forced_hash: 3932521563
    forced_addr: 4
    global_addr: global_forced_addr
    set_action:
      - script.execute: script_save_changes
    on_value:        # set or clear in_use template binary sensor depending on whether power usage is above threshold
      - lambda: id(in_use).publish_state(id(wattage).state >= x);

  - platform: template
    name: $device_name Blue LED Brightness
    min_value: 1
    max_value: 100
    step: 1
    initial_value: 75
    id: blue_led_brightness
    entity_category: config
    optimistic: true
    restore_value: true
    unit_of_measurement: "%"
    mode: slider
    icon: mdi:brightness-percent
    set_action:
      - script.execute: script_save_changes
    on_value:
      - lambda: if ( id(blue_led).state ) id(blue_led_pwm).set_level(x/100);
    forced_hash: 2635887862
    forced_addr: 46
    global_addr: global_forced_addr

  - platform: template
    name: $device_name Red LED Brightness
    min_value: 1
    max_value: 100
    step: 1
    initial_value: 75
    id: red_led_brightness
    entity_category: config
    optimistic: true
    restore_value: true
    unit_of_measurement: "%"
    mode: slider
    icon: mdi:brightness-percent
    set_action:
      - script.execute: script_save_changes
    on_value:
      - lambda: if ( id(red_led).state ) id(red_led_pwm).set_level(x/100);
    forced_hash: 4192312897
    forced_addr: 50
    global_addr: global_forced_addr

  - platform: template
    name: $device_name Scale Power
    min_value: 50
    max_value: 200
    step: .1
    initial_value: $sub_default_scale_power
    id: scale_power
    entity_category: config
    optimistic: true
    restore_value: true
    unit_of_measurement: "%"
    mode: box
    disabled_by_default: $disable_entities
    forced_hash: 3565176138
    forced_addr: 56
    global_addr: global_forced_addr
    set_action:
      - script.execute: script_save_changes
    on_value:   # republish value. Sensor automation applies new scaling factor.
      - lambda: id(wattage).publish_state(id(wattage).get_raw_state());

  - platform: template
    name: $device_name Scale Current
    min_value: 50
    max_value: 200
    step: .1
    initial_value: $sub_default_scale_current
    id: scale_current
    entity_category: config
    optimistic: true
    restore_value: true
    unit_of_measurement: "%"
    mode: box
    disabled_by_default: $disable_entities
    forced_hash: 2293595686
    forced_addr: 58
    global_addr: global_forced_addr
    set_action:
      - script.execute: script_save_changes
    on_value:   # republish value. Sensor automation applies new scaling factor.
      - lambda: id(current).publish_state(id(current).get_raw_state());

  - platform: template
    name: $device_name Scale Voltage
    min_value: 50
    max_value: 200
    step: .1
    initial_value: $sub_default_scale_voltage
    id: scale_voltage
    entity_category: config
    optimistic: true
    restore_value: true
    unit_of_measurement: "%"
    mode: box
    disabled_by_default: $disable_entities
    forced_hash: 254525215
    forced_addr: 60
    global_addr: global_forced_addr
    set_action:
      - script.execute: script_save_changes
    on_value:   # republish value. Sensor automation applies new scaling factor.
      - lambda: id(voltage).publish_state(id(voltage).get_raw_state());

  - platform: template
    name: $device_name Debounce Time
    min_value: $sub_min_debounce
    max_value: 2000
    step: 1
    initial_value: $sub_default_debounce
    id: number_debounce
    entity_category: config
    optimistic: true
    restore_value: true
    unit_of_measurement: "ms"
    mode: box
    disabled_by_default: $disable_entities
    forced_hash: 2232959069
    forced_addr: 40
    global_addr: global_forced_addr

# emulate status_led
# https://esphome.io/guides/automations.html#interval-component
interval:
  - interval: 5s
    then:
    - lambda: |-
        if ( ( ((App.get_app_state() & STATUS_LED_ERROR  ) != 0u) ||
               ((App.get_app_state() & STATUS_LED_WARNING) != 0u) )
            && !id(blink_status_led).is_running() )
          id(blink_status_led).execute();


# Current reserved flash memory:
# 00-01: Power Monitoring Mode
# 02-03: Relay output
# 04-05: Use Threshold
# 06-07: Total Daily Energy
# 08-33: Wi-Fi Credentials
# 34-35: Button Config select entity
# 36-37: Blue LED select entity
# 38-39: Red LED select entity
# 40-41: Debounce number entity
# 42-43: No HASS switch
# 44-45: Blue LED
# 46-47: Blue LED Brightness
# 48-49: Red LED
# 50-51: Red LED Brightness
# 56-57: Scale Power
# 58-59: Scale Current
# 60-61: Scale Voltage
# 62-63: Early Publish Switch
# 74-75: Boot State select entity
