substitutions:
  api_key: "Change me"
  # Required import substitutions
  device_site: "home"
  device_location_code: "changeme"
  device_location_name: "Change Me"
  device_type_code: "plg"
  device_type_name: "Smart Plug"
  device_ip: "0.0.0.0"

  # https://esphome.io/components/switch/gpio.html?highlight=restore_mode
  sub_restore_mode: RESTORE_DEFAULT_ON  # overwrite to change boot up behavior of relay

  disable_entities:  "true"     # set to "false" to have all entities show up in Home Assistant automatically
  disable_webserver: "false"    # set to "true" to disable the webserver listening on port 80.

  # substitutions for button actions.  on_press and on_release implement a timer scheme with configurable delay.
  # on_hold_30s re-enables the AP and captive portal for the precompiled update binary.
  # any length of hold can be implemented with just on_press and on_release using the following directions.  This
  # is basically how this yaml file works.
  #   * have a delay for the desired hold in the on_press script
  #   * stop the on_press script in the on_release script
  #   * place actions in the on_press script after the delay to perform them while still holding the button
  #   * place actions in the on_release script, with the condition that the on_press script is not running, to
  #     perform them on release of the button.
  sub_on_press:         script_do_nothing  # executes right when button is initially pressed
  sub_on_release:       script_do_nothing  # executes right when button is released
  sub_on_hold_30s:      script_force_ap    # executes right when button has been held for 5s, while button is still being held

  sub_on_turn_on:       script_do_nothing
  sub_on_turn_off:      script_do_nothing

  # an extra script that, if running, will stop the relay from toggling on button release.
  # used to not toggle when WiFi AP is re-enabled on update bin file.
  sub_toggle_check: script_force_ap

  # made this a substitution so that the update bin file and yaml compiled versions can have different defaults
  default_button_config: "Toggle on Press"

  # substitutions for power monitoring calibration.  Allows end users to change calibration in their yaml and still
  # incorporate this file as a package to get all the updates we release.
  current_resistor_val: "0.001"
  voltage_divider_val:  "2001"
  sub_hlw_model:         BL0937
  power_cal_val1_in:    "0.0"
  power_cal_val1_out:   "0.0"
  power_cal_val2_in:    "879.4"
  power_cal_val2_out:   "750"
  current_cal_val1_in:  "0.0"
  current_cal_val1_out: "0.0"
  current_cal_val2_in:  "6.8"
  current_cal_val2_out: "3.5"
  voltage_cal_val1_in:  "0.0"
  voltage_cal_val1_out: "0.0"
  voltage_cal_val2_in:  "132.7"
  voltage_cal_val2_out: "119.1"

  sub_default_scale_power: "87"
  sub_default_scale_current: "162"
  sub_default_scale_voltage: "85"

  # set default power monitoring update interval in yaml.
  # this will only be effective as long as the select entity is set to "YAML Configured"
  sub_update_interval: 10s
  sub_pm_initial_option: YAML Configured ($sub_update_interval)

  sub_hlw_timeout: 3s

  # for early sensor publishing
  sub_early_publish_percent:           "25"
  sub_early_publish_percent_min_power: "0.5"
  sub_early_publish_absolute:          "16.68" # for PLF10, 1w is approximately 5.56.  16.68 is approximately 3w.

  # GPIO definitions
  sub_pm_sel_pin:   GPIO12
  sub_pm_cf_pin:    GPIO5
  sub_pm_cf1_pin:   GPIO14
  sub_button_pin:   GPIO13
  sub_blue_led_pin: GPIO2
  sub_red_led_pin:  GPIO0
  sub_relay_pin:    GPIO4

  # debounce specifications
  sub_default_debounce: "20"
  sub_min_debounce:     "10"

  sub_reboot_req: '9'
  sub_ota_num_attempts: '15'
  sub_api_reboot_timeout: 0s

 # Project Substitutions (not intended for user substitutions)
  package_url: "github://Marsupilami23/myesphometemplates/kauf-plf12-plug.yaml@main"

# Allow importing this package
dashboard_import:
  package_import_url: "${package_url}"
  import_full_config: false

# https://esphome.io/components/external_components.html
external_components:
  - source:
      type: git
      url: https://github.com/KaufHA/common
      ref: v2024.11.20
    refresh: always

# Import packages:
packages:
  standard_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - kauf-plf12-plug/standard/project.yaml
      - kauf-plf12-plug/standard/diagnostics.yaml
      - kauf-plf12-plug/standard/wifi.yaml
  cree_st19_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - kauf-plf12-plug/board.yaml
      - kauf-plf12-plug/binary-sensors.yaml
      - kauf-plf12-plug/scripts.yaml
      - kauf-plf12-plug/pwm-outputs.yaml
      - kauf-plf12-plug/buttons.yaml
      - kauf-plf12-plug/sensors.yaml

switch:
  # relay output
  # https://esphome.io/components/switch/gpio.html
  - platform: gpio
    id: relay
    name: $device_name
    pin: $sub_relay_pin
    entity_category: ''
    forced_hash: 41191675
    forced_addr: 2
    global_addr: global_forced_addr
    restore_mode: $sub_restore_mode
    on_turn_on:
        - script.execute: script_set_power_leds
        - script.execute: $sub_on_turn_on
    on_turn_off:
        - script.execute: script_set_power_leds
        - script.execute: $sub_on_turn_off

    # https://esphome.io/components/switch/template.html
  - platform: template
    id: switch_no_hass
    name: $device_name No HASS
    optimistic: true
    entity_category: config
    disabled_by_default: $disable_entities
    icon: mdi:toggle-switch-off-outline
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - lambda: |-
          id(kauf_api).set_reboot_timeout(0);  // 0 disables auto rebooting and also new status led blinking.  doesn't stop current status led blinking
          id(kauf_api).status_clear_warning(); // stops current status led blinking, timeout 0 keeps it from restarting
      - script.execute: script_save_changes
    on_turn_off:
      - lambda: id(kauf_api).set_reboot_timeout(900000);
      - script.execute: script_save_changes
    forced_hash: 657159011
    forced_addr: 42
    global_addr: global_forced_addr

  - platform: template
    id: blue_led
    name: $device_name Blue LED
    optimistic: true
    entity_category: config
    disabled_by_default: $disable_entities
    icon: mdi:led-outline
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(blue_led_pwm).set_level(id(blue_led_brightness).state/100);
    on_turn_off:
      - lambda: id(blue_led_pwm).set_level(0.0);
    forced_hash: 1329407616
    forced_addr: 44
    global_addr: global_forced_addr

  - platform: template
    id: red_led
    name: $device_name Red LED
    optimistic: true
    entity_category: config
    disabled_by_default: $disable_entities
    icon: mdi:led-outline
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(red_led_pwm).set_level(id(red_led_brightness).state/100);
    on_turn_off:
      - lambda: id(red_led_pwm).set_level(0.0);
    forced_hash: 261191305
    forced_addr: 48
    global_addr: global_forced_addr

  - platform: template
    id: switch_early_publish
    name: $device_name Early Publish
    optimistic: true
    entity_category: config
    disabled_by_default: $disable_entities
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - lambda: id(hlw_main).enable_early_publish();
    on_turn_off:
      - lambda: id(hlw_main).disable_early_publish();
    forced_hash: 1334841796
    forced_addr: 62
    global_addr: global_forced_addr

# emulate status_led
# https://esphome.io/guides/automations.html#interval-component
interval:
  - interval: 5s
    then:
    - lambda: |-
        if ( ( ((App.get_app_state() & STATUS_LED_ERROR  ) != 0u) ||
               ((App.get_app_state() & STATUS_LED_WARNING) != 0u) )
            && !id(blink_status_led).is_running() )
          id(blink_status_led).execute();


# Current reserved flash memory:
# 00-01: Power Monitoring Mode
# 02-03: Relay output
# 04-05: Use Threshold
# 06-07: Total Daily Energy
# 08-33: Wi-Fi Credentials
# 34-35: Button Config select entity
# 36-37: Blue LED select entity
# 38-39: Red LED select entity
# 40-41: Debounce number entity
# 42-43: No HASS switch
# 44-45: Blue LED
# 46-47: Blue LED Brightness
# 48-49: Red LED
# 50-51: Red LED Brightness
# 56-57: Scale Power
# 58-59: Scale Current
# 60-61: Scale Voltage
# 62-63: Early Publish Switch
# 74-75: Boot State select entity
