substitutions:
  # User-required substitutions
  device_site: "home"
  device_location_code: "bedroom01"
  device_location_name: "Bedroom 1"
  device_type_code: "4cpc"
  device_type_name: "4ch PWM Controller"
  device_number: "089"
  device_ip: "0.0.0.0"

  timing_press_threshold: "300ms"

  # Project Substitutions (not intended for user substitution)
  device_model: "RGBW2"
  device_make: "Shelly"
  package_version: "2024.2.15"
  package_url: "github://mariodivece/esphometemplates/shelly-rgbw2-4ch.yaml@main"

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - standard/project.yaml
      - standard/diagnostics.yaml
      - standard/wifi.yaml
      
  shelly_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - shelly-rgbw2/board.yaml
      - shelly-rgbw2/status-led.yaml
      - shelly-rgbw2/pwm-outputs.yaml
      - shelly-rgbw2/current-sensor.yaml
      - shelly-rgbw2/scripts-4ch.yaml
      - shelly-rgbw2/input-switch.yaml
      - shelly-rgbw2/virtual-buttons.yaml

light:

  - platform: monochromatic
    name: "Channel 1 (R)"
    id: light_ch1
    output: pwm_out_ch1

  - platform: monochromatic
    name: "Channel 2 (G)"
    id: light_ch2
    output: pwm_out_ch2

  - platform: monochromatic
    name: "Channel 3 (B)"
    id: light_ch3
    output: pwm_out_ch3

  - platform: monochromatic
    name: "Channel 4 (W)"
    id: light_ch4
    output: pwm_out_ch4
