substitutions:
  sub_name: "changeme"
  sub_friendly_name: "Change Me"
  sub_ap_timeout: 15s


  disable_entities: "true"

# Import packages:
packages:
  standard_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: dev
    refresh: always
    files:
      - wb2l/standard/project.yaml
      - wb2l/standard/diagnostics.yaml
      - wb2l/standard/wifi.yaml
  dogain_rgbww_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: dev
    refresh: always
    files:
      - wb2l/board.yaml
