substitutions:
  api_key: ""
  device_site: "home"
  device_location_code: "changeme"
  device_location_name: "Change Me"
  device_type_code: "snsr"
  device_type_name: "Sensor"

  # GPIO pin designations
  sub_binary_sensor_gpio: GPIO08
  sub_activity_led_gpio:  GPIO26
  sub_batt_dv_gpio:       GPIO14
  sub_batt_lvl_gpio:      GPIO23
  sub_reset_button_gpio:  GPIO20

  # Max power
  sub_max_power: "0.8"

packages:
  standard_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - xfox-door-sensor-tester/standard/project.yaml
      - xfox-door-sensor-tester/standard/wifi.yaml
      - xfox-door-sensor-tester/standard/diagnostics.yaml
  xfox_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - xfox-door-sensor-tester/board.yaml

# Adds a restart function throught the yaml and a button in HA      
button:
  - platform: restart
    id: restart_button
    name: "${device_name} Restart Firmware"
    entity_category: diagnostic
    disabled_by_default: $disable_entities

# Adds Activity LED function and maps to GPIO pin.
output:
  - platform: libretiny_pwm
    id: activity_led_output
    frequency: 1000 Hz
    pin:
      number: "${sub_activity_led_gpio}"

binary_sensor:
  - platform: gpio
    device_class: door
    name: "${device_name}"
    pin:
      number: "${sub_binary_sensor_gpio}"
      allow_other_uses: true
    on_state:
      - if:
          condition:
            - switch.is_off: manual_mode
          then:
            - output.turn_on: activity_led_output
            - delay: 5000ms
            - output.turn_off: activity_led_output
          else:
            - light.turn_on:
                id: activity_led
                effect: pulse
      - script.execute: script_deep_sleep
    icon: mdi:door

  - platform: gpio
    id: bottom_button
    pin:
      number: "${sub_reset_button_gpio}"
      inverted: true
      allow_other_uses: true
    name: "Bottom Button"
    icon: mdi:button-pointer
    on_state:
      - script.execute: script_check_deep_sleep
    on_multi_click:
      - timing:
          - on for at least 1s
        then:
          - switch.toggle: manual_mode

switch:
  - platform: gpio
    id: batt_dv
    pin: $sub_batt_dv_gpio

  - platform: template
    optimistic: True
    name: Manual Mode
    id: manual_mode
    on_turn_off:
      - script.execute: script_check_deep_sleep
    on_turn_on:
      - script.execute: script_check_deep_sleep
      - light.turn_on:
          id: activity_led
          effect: pulse
    entity_category: config
    icon: mdi:sleep-off
