substitutions:
  api_key: ""
  device_site: "home"
  # Device Location Codes: front yard (fy), Front Porch (fp), Garage (grg),
  # Laundry Room (laurm), Small Bathroom (smlbr) Living Room (lvrm), Family Room (fmrm),
  # Dining Room (dngrm), Kitchen (ktcn), Office Space (offspc), Hallway (hlwy),
  # Craftroom (cftrm), Guest Room (gstrm), Middle Bathroom (mdlbr), Master Bedroom (mstrbdrm),
  # Master Bathroom (mstrbr)
  device_room_code: "changeme"
  # Device location code: Door (dr), Window (wdw), Lamp (lmp)  
  device_location_code: "changeme"
  # Device type codes: Sensor (snsr), Window Sensor (wdwsnr), RGB Light Bulb (rgblb),
  # Warm/Cold Light Bulb (wclb), Light Switch (ltswtch)
  device_type_code: "changeme"
  # Used for Friendly Name
  device_room_name: "Change Me"
  device_location_name: "Change Me"
  device_type_name: "Change Me"
  
  disable_entities: "true"

  # GPIO pin designations
  sub_binary_sensor_gpio: GPIO08
  sub_activity_led_gpio:  GPIO26
  sub_batt_dv_gpio:       GPIO14
  sub_batt_lvl_gpio:      GPIO23
  sub_reset_button_gpio:  GPIO20

  # Max power
  sub_max_power: "0.8"

external_components:
  - source:
      type: git
      url: https://github.com/Marsupilami23/myesphometemplates
      ref: main
    components: [ api, deep_sleep_libretiny, mqtt ]
    refresh: always

packages:
  standard_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - xfox-door-sensor/standard/project.yaml
      - xfox-door-sensor/standard/wifi.yaml
      - xfox-door-sensor/standard/diagnostics.yaml
  xfox_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - xfox-door-sensor/board.yaml
      - xfox-door-sensor/scripts.yaml

# Adds Activity LED function and maps to GPIO pin.
output:
  - platform: libretiny_pwm
    id: activity_led_output
    frequency: 1000 Hz
    pin:
      number: "${sub_activity_led_gpio}"
      inverted: true
    
switch:
  - platform: gpio
    id: batt_dv
    pin: $sub_batt_dv_gpio

  - platform: template
    optimistic: True
    name: Manual Mode
    id: manual_mode
    on_turn_off:
      - script.execute: PLACEHOLDER FOR NEW SCRIPT
    on_turn_on:
      - script.execute: PLACEHOLDER FOR NEW SCRIPT
      - light.turn_on:
          id: activity_led
          effect: pulse
    entity_category: config
    icon: mdi:sleep-off



light:
  - platform: monochromatic
    name: "Activity LED"
    output: activity_led_output
    id: activity_led
    icon: mdi:lamp
    effects:
      - strobe:
      - pulse:
          transition_length:
            on_length: 1s
            off_length: 2s
          update_interval: 3s

deep_sleep_libretiny:
  id: deep_sleep_lt
  sleep_duration: 24h
  run_duration: 30s
  wakeup_pins:
    - pin:
        number: "${sub_reset_button_gpio}"
        allow_other_uses: true
        mode:
          input: True
          pullup: True
        inverted: True
      wakeup_pin_mode: KEEP_AWAKE
    - pin:
        number: "${sub_binary_sensor_gpio}"
        allow_other_uses: true
        mode:
          input: True
      wakeup_pin_mode: INVERT_WAKEUP
