substitutions:
  api_key: ""
  device_site: "home"
  device_location_code: "changeme"
  device_location_name: "Change Me"
  device_type_code: "snsr"
  device_type_name: "Sensor"

  # GPIO pin designations
  sub_binary_sensor_gpio: GPIO08
  sub_activity_led_gpio:  GPIO26
  sub_batt_dv_gpio:       GPIO14
  sub_batt_lvl_gpio:      GPIO23
  sub_reset_button_gpio:  GPIO20

  # Max power
  sub_max_power: "0.8"

packages:
  standard_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - xfox-door-sensor-tester/standard/project.yaml
      - xfox-door-sensor-tester/standard/wifi.yaml
      - xfox-door-sensor-tester/standard/diagnostics.yaml
  xfox_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - xfox-door-sensor-tester/board.yaml
      
button:
  - platform: restart
    id: restart_button
    name: "${device_name} Restart Firmware"
    entity_category: diagnostic
    disabled_by_default: $disable_entities
