substitutions:
  api_key: ""
  device_site: "home"
  # Device Location Codes: front yard (fy), Front Porch (fp), Garage (grg),
  # Laundry Room (laurm), Small Bathroom (smlbr) Living Room (lvrm), Family Room (fmrm),
  # Dining Room (dngrm), Kitchen (ktcn), Office Space (offspc), Hallway (hlwy),
  # Craftroom (cftrm), Guest Room (gstrm), Middle Bathroom (mdlbr), Master Bedroom (mstrbdrm),
  # Master Bathroom (mstrbr)
  device_room_code: "changeme"
  # Device location code: Door (dr), Window (wdw), Lamp (lmp)  
  device_location_code: "changeme"
  # Device type codes: Sensor (snsr), Window Sensor (wdwsnr), RGB Light Bulb (rgblb),
  # Warm/Cold Light Bulb (wclb), Light Switch (ltswtch)
  device_type_code: "changeme"
  # Used for Friendly Name
  device_room_name: "Change Me"
  device_location_name: "Change Me"
  device_type_name: "Change Me"
  
  disable_entities: "true"

  # GPIO pin designations
  sub_binary_sensor_gpio: GPIO08
  sub_activity_led_gpio:  GPIO26
  sub_batt_dv_gpio:       GPIO14
  sub_batt_lvl_gpio:      GPIO23
  sub_reset_button_gpio:  GPIO20

  # Max power
  sub_max_power: "0.8"

external_components:
  - source:
      type: git
      url: https://github.com/Marsupilami23/myesphometemplates
      ref: main
    components: [ api, deep_sleep_libretiny, mqtt ]
    refresh: always

packages:
  standard_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: dev
    refresh: always
    files:
      - xfox-door-sensor/standard/project.yaml
      - xfox-door-sensor/standard/wifi.yaml
      - xfox-door-sensor/standard/diagnostics.yaml
  xfox_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: dev
    refresh: always
    files:
      - xfox-door-sensor/deep_sleep.yaml
      - xfox-door-sensor/binary_sensor.yaml
      - xfox-door-sensor/text_sensor.yaml
      - xfox-door-sensor/sensor.yaml
      - xfox-door-sensor/light.yaml
      - xfox-door-sensor/switch.yaml
      - xfox-door-sensor/board.yaml
      - xfox-door-sensor/scripts.yaml
