substitutions:
  # Generated name and unique device id for the device
  # Not intended for user substitutions
  device_name: "${device_room_name} ${device_location_name} ${device_type_name}"
  device_code: "${device_room_code}-${device_location_code}-${device_type_code}"
  device_model: "RGBWW"
  device_make: "DOGAIN"
  project_ver_num: "1.971"
  project_ver_let: y
  
# Allow importing this package
dashboard_import:
  package_import_url: "github://Marsupilami23/myesphometemplates/dogain-rgbww-bulbs-esp8266/standard/project.yaml@main"
  import_full_config: false

# https://esphome.io/guides/automations.html#global-variables
globals:
  - id: global_quick_boot_count
    type: int
    restore_value: yes
    initial_value: '0'


# https://esphome.io/components/esphome.html
esphome:
  name: "${device_code}"
  friendly_name: "${device_name}"
  comment: "${device_model} bulb by ${device_make}"
  name_add_mac_suffix: false
  min_version: "2024.11.0"
  project:
    name: "${device_make}.${device_model}"
    version: $project_ver_num($project_ver_let)
  on_boot:
    then:
        # set default values for template sensors, otherwise they are unknown.
      - binary_sensor.template.publish:
          id: sensor_4m
          state: $sub_4m
      - script.execute: script_quick_boot
    min_version: 2026.1.1
