substitutions:
  log_level: DEBUG

# Enable logging bia network and disable serial port
logger:
  level: "${log_level}"
  baud_rate: 115200
  
http_request:
  id: burn_check_request
  verify_ssl: false

time:
  - platform: homeassistant    

binary_sensor:
  # Diagnostic sensor for connection
  - platform: status
    name: "API Status"
    id: sensor_status
    disabled_by_default: true

  - platform: gpio
    id: test_button
    name: Test Button
    pin: "${sub_test_button}"
    on_press:
      then:
        - logger.log: "Button Pressed"      

sensor:
  - platform: template
    id: burn_status
    name: "Burn Status"
    icon: mdi:fire
    on_value:
      - if:
          condition:
            - lambda: return id(burn_status).state == 6;
          then:
            - light.turn_on:
                id: burn_status_rgb
                brightness: 25%
                red: 0%
                green: 100%
                blue: 0%
      - if:
          condition:
            - lambda: return id(burn_status).state == 7 || id(burn_status).state == 8;
          then:
            - light.turn_on:
                id: burn_status_rgb
                brightness: 25%
                red: 100%
                green: 50%
                blue: 0%
      - if:
          condition:
            - lambda: return id(burn_status).state == 9;
          then:
            - light.turn_on:
                id: burn_status_rgb
                brightness: 25%
                red: 100%
                green: 0%
                blue: 0%
    
light:
  - platform: rgb
    id: burn_status_rgb
    name: "Burn_Status_LEDs"
    red: red_led
    green: green_led
    blue: blue_led
            
# Provide a pre-built button for restart the device
button:
  - platform: restart
    name: "Reboot Device"
    id: button_restart
    icon: mdi:power-cycle
    entity_category: "diagnostic"
