substitutions:
  log_level: DEBUG
  sub_baud_rate: "115200"
  
globals:
  - id: burn_category
    type: int
    restore_value: true
    initial_value: "0"
    
# Enable logging bia network and disable serial port
logger:
  level: "${log_level}"
  baud_rate: "${sub_baud_rate}"

http_request:
  id: burn_check_request
  verify_ssl: false

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  # Diagnostic sensor for connection
  - platform: status
    name: "API Status"
    id: sensor_status
    disabled_by_default: true
  - platform: gpio
    name: "Test Button"
    id: test_button
    pin: "${sub_wake_pin}"
    on_state:
      then:
        - logger.log: "Button Pressed"
        - script.execute: get_burn_category
        - script.execute: set_burn_category
        - script.execute: set_burn_category_grb

text_sensor:
  - platform: template
    id: burn_status
    name: "Burn Status"
    icon: mdi:fire
 
    
light:
  - platform: monochromatic
    id: user_led
    name: "User LED"
    output: pwm_user_led
    restore_mode: ALWAYS_ON
  - platform: neopixelbus
    id: burn_status_grb
    type: GRB
    variant: WS2812X
    pin: "${sub_neopixelbus_pin}"
    num_leds: 64
    name: "NeoPixel Lights"
    restore_mode: ALWAYS_OFF

sensor:
  - platform: template
    id: burn_status_sensor
    name: "Burn Status Category"
    icon: "mdi:fire"
  
# Provide a pre-built button for restart the device
button:
  - platform: restart
    name: "Reboot Device"
    id: button_restart
    icon: mdi:power-cycle
    entity_category: "diagnostic"
  - platform: template
    name: "Get Burn Status"
    id: get_burn_status
    icon: mdi:fire-alert
    entity_category: "diagnostic"
