substitutions:
  log_level: DEBUG

# Enable logging bia network and disable serial port
logger:
  level: "${log_level}"
  baud_rate: 115200

binary_sensor:
  # Diagnostic sensor for connection
  - platform: status
    name: "API Status"
    id: sensor_status
    disabled_by_default: true
    
  - platform: burn_forecast
    name: "Burn Status"
    id: burn_status
    unit_of_measurement: ""
    state_class: measurement
    icon: mdi:fire
    update_interval: 300s # every 5 minutes
    url: https://sonomatech-production.s3.amazonaws.com/sacramento/airquality_org/cbyb-widget/burncheckForecast.txt
      
# Provide a pre-built button for restart the device
button:
  - platform: restart
    name: "Reboot Device"
    id: button_restart
    icon: mdi:power-cycle
    entity_category: "diagnostic"
