# https://esphome.io/components/esphome.html
esphome:
  name: "${sub_name}"
  friendly_name: "${sub_friendly_name}"
  name_add_mac_suffix: false
  min_version: "2024.11.0"
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio 

external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: release
    components: [ "http_request", "json" ]
    refresh: always

deep_sleep:
  id: deep_sleep
  sleep_duration:
    days: 1
  wakeup_pin:
    number: "${sub_test_button}"
    allow_other_uses: true
  wakeup_pin_mode: KEEP_AWAKE
