# https://esphome.io/components/esphome.html
esphome:
  name: "${sub_name}"
  friendly_name: "${sub_friendly_name}"
  name_add_mac_suffix: false
  min_version: "2024.11.0"
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio 

external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: release
    components: [ "http_request", "json" ]
    refresh: always

deep_sleep:
  run_duration: 1d
  wakeup_interval: 60s 

  on_wake:
    - lambda: |-
        // Get the current time
        auto now = id(homeassistant_time).now();

        // Check if it's 12:01:00 AM
        if (now.hour == 0 && now.minute == 1) {
          // Trigger the http_request to update the burn category
          id(burn_category
