# https://esphome.io/components/esphome.html
esphome:
  name: "${sub_name}"
  friendly_name: "${sub_friendly_name}"
  name_add_mac_suffix: false
  min_version: "2024.11.0"
  libraries:
    - ArduinoJson=https://https://github.com/bblanchon/ArduinoJson/releases/tag/v7.2.1
