substitutions:
  # WIFI Substitutions
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password
  sub_ota_num_attempts: "15"

sensor:
  - platform: wifi_signal
    name: "RSSI"
    id: sensor_rssi
    update_interval: 60s
    entity_category: "diagnostic"

api:

# Enable OTA
ota:
  - platform: esphome
    id: my_ota
    password: "${ota_password}"
    on_error:
      then:
        - button.press: button_restart
    on_begin:
      then:
        - light.turn_on: user_led
        - logger.log: "Begining Firmware Update!"
#        - deep_sleep.prevent: deep_sleep_1
    on_end:
      then:
        - light.turn_off: user_led
        - logger.log: "Update completed!"
safe_mode:
  num_attempts: "${sub_ota_num_attempts}"
  
# Enable WIFI and AP for capitve portal
wifi:
  id: wifi_brg95758
  fast_connect: false
  power_save_mode: none
  output_power: 8.5dB
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  ap:
    ssid: "${sub_name}-setup"
    password: "${wifi_password}"

web_server:
  version: 3
  include_internal: true
  ota: true

captive_portal:
