# Allow importing this package
dashboard_import:
  package_import_url: "${package_url}"
  import_full_config: false
    
binary_sensor:
  # Make the status LED blink when not connected/trying to connect
  - platform: template
    name: "API connected"
    id: sensor_api_connected
    internal: true
    entity_category: "diagnostic"
    device_class: "connectivity"
    lambda: return global_api_server->is_connected();
    on_press:
      - light.turn_off: led_status
    on_release:
      - light.turn_on: led_status
