# NOTE: This file is not a stand-alone package. it is part of
# a 'root' device template and expects the substitutions that
# are hereby referenced to be defined by it's parent.

substitutions:
  log_level: INFO
  timezone: "America/Los_Angeles"
  
# Allow importing of this package
dashboard_import:
  package_import_url: "github://Marsupilami23/myesphometemplates/cree-st19-bulbs/standard/diagnostics.yaml@main"
  import_full_config: false
  
# Enable logging bia network and disable serial port
logger:
  level: "${log_level}"
  baud_rate: 0

# Provide date and time
time:
  - platform: sntp
    id: time_service
    timezone: "${timezone}"

# Diagostic output sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: "IP Address"
      icon: "mdi:wan"

binary_sensor:
  # Diagnostic sensor for connection
  - platform: status
    name: "API Status"
    id: sensor_status
    disabled_by_default: true

  # Captures the uptime and updates the human-readable
  # text sensor displayed. this is an internal sensor only.
sensor:
  - platform: uptime
    name: Uptime
    update_interval: 60s
    entity_category: diagnostic

# Provide a pre-built button for restart the device
button:
  - platform: restart
    id: restart_button
    name: Restart Firmware
    icon: mdi:power-cycle
    entity_category: "diagnostic"

  # Provide a button to reset all defined flash settings.
  - platform: factory_reset
    disabled_by_default: false
    name: "Load Factory Settings"
    id: factory_reset_all
    icon: mdi:factory
