# NOTE: This file is not a stand-alone package. It is part of 
# a 'root' device template and expects the substitutions that
# are hereby referenced to be defined by it's parent.

substitutions:
  # Generated name and unique device id for the device
  # Not intended for user substitutions
  device_name: "${device_room_name} ${device_location_name} ${device_type_name}"
  device_code: "${device_room_code}-${device_location_code}-${device_type_code}"
  device_model: "ST19"
  device_make: "CREE"
  package_version: "2024.11.20"

# Allow importing of this package
dashboard_import:
  package_import_url: "github://Marsupilami23/myesphometemplates/cree-st19-bulbs/standard/project.yaml@main"
  import_full_config: false
  
# Define a globale variable for CPU speed
globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"
  - id: global_force_addr
    type: int
    restore_value: no
    initial_value: "12345"
  - id: global_quick_boot_count
    type: int
    restore_value: yes
    initial_value: "0"

# Setup the integration and define some project variables
esphome:
  name: "${device_code}"
  friendly_name: "${device_name}"
  comment: "${device_model} bulb by ${device_make}"
  name_add_mac_suffix: false
  min_version: "2024.10.0"
  project:
    name: "${device_make}.${device_model}"
    version: "${package_version}"
  on_boot:
    - priority: 900.0
      then:
        - lambda: |-
            id(cpu_speed) = ESP.getCpuFreqMHz();

text_sensor:
  # Show firmware template version
  - platform: template
    name: "Deployment Version"
    lambda: return {"${package_version}"};
    disabled_by_default: true
    icon: "mdi:tag"
    entity_category: diagnostic

sensor:
  # Device CPU Frequency
  - platform: template
    name: "CPU Frequency"
    icon: "mdi:speedometer"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    disabled_by_default: true
    lambda: |-
      return (id(cpu_speed));
    entity_category: diagnostic
