# NOTE: This file is not a stand-alone package. It is part of
# a 'root' device template and expects the substitutions that
# are hereby referenced to be defined by it's parent.

substitutions:
  # WIFI Substitutions
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password

# Enable Home Assistant API
api:
  encryption:
    key: "${api_key}"

sensor:
  - platform: wifi_signal
    name: "RSSI"
    id: sensor_rssi
    update_intervals: 60s
    entity_category: "diagnostic"

# Enable OTA
ota:
  safe_mode: true
  password: "${ota_password}"

# Enable WIFI and AP for capitve portal
wifi:
  fast_connect: false
  power_save_mode: none
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  ap:
    ssid: "${device_code}-setup"
    password: "${wifi_password}"

captive_portal:
