
substitutions:
  # Generated name and unique device id for the device
  # Not intended for user substitutions
  device_name: "${device_location_name} - ${device_type_name}"
  device_code: "${device_location_code}-${device_type_code}"
  device_model: "Door Sensor"
  device_make: "XFOX"
  package_version: "2024.11.20"

# Allow importing this package
dashboard_import:
  package_import_url: "github://Marsupilami23/myesphometemplates/dogain-rgbww-bulbs-bk72xx/standard/project.yaml@main"
  import_full_config: false
  
# https://esphome.io/components/esphome.html
esphome:
  name: "${device_code}"
  friendly_name: "${device_name}"
  comment: "${device_model} by ${device_make}"
  name_add_mac_suffix: false
  min_version: "2024.11.0"
  project:
    name: "${device_make}.${device_model}"
    version: "${package_version}"
