# Cree Sample YAML file.
substitutions:
  device_location_code: "frontyardpost"
  device_location_name: "Front Yard Post"
  device_type_code: "2cbulb"
  device_type_name: "Light"

  packages:
    cree.st19: github://Marsupilami23/cree-st19-bulbs.yaml
