# DOGAIN RGBWW bk72xx Bulb Sample YAML file.
substitutions:
  api_key: ""
  device_site: "home"
  # Device Location Codes: front yard (fy), Front Porch (fp), Garage (grg),
  # Laundry Room (laurm), Small Bathroom (smlbr) Living Room (lvrm), Family Room (fmrm),
  # Dining Room (dngrm), Kitchen (ktcn), Office Space (offspc), Hallway (hlwy),
  # Craftroom (cftrm), Guest Room (gstrm), Middle Bathroom (mdlbr), Master Bedroom (mstrbdrm),
  # Master Bathroom (mstrbr)
  device_room_code: "changeme"
  # Device location code: Door (dr), Window (wdw), Bedside (bdsd), Floor (flr), pendant (pndnt), ceiling fan (clgfn) 
  device_location_code: "changeme"
  # Device type codes: Sensor (snsr), Window Sensor (wdwsnr), RGBWW Light Bulb (rgbwwblb),
  # Warm/Cold Light Bulb (wclb), Light Switch (ltswtch)
  device_type_code: "changeme"
  # Used for Friendly Name
  device_room_name: "Change Me"
  device_location_name: "Change Me"
  device_type_name: "Change Me"

packages:
  DOGAIN_RGBWW_packages:
    url: https://github.com/Marsupilami23/myesphometemplates
    ref: main
    refresh: always
    files:
      - dogain-rgbww-bulbs-bk72xx.yaml
