substitutions:
  device_name: "My Sample Device 1"
  device_code: "my-sample-device-01"

packages:
  somepackagename:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    file: samples/scrapbook.yaml
    refresh: 0s
    
wifi:
  use_address: "192.168.1.11"
