# XFOX Door Sensor Sample YAML file.
substitutions:
  api_key: ""
  device_location_code: "changeme"
  device_location_name: "Change Me"
  device_type_code: "snsr"
  device_type_name: "Sensor"

packages:
  XFOX_DOOR_SENSOR_packages:
    url: https://github.com/Marsupilami23/myesphometemplates/
    ref: main
    refresh: always
    files:
      - xfox-door-sensor.yaml
