substitutions:
  # Generated name and unique device id for the device
  # Not intended for user substitutions
  device_name: "${device_location_name} - ${device_type_name}"
  device_code: "${device_location_code}-${device_type_code}"
  device_model: "PLF12"
  device_make: "KAUF"
  package_version: "2024.11.20"

# Allow importing of this package
dashboard_import:
  package_import_url: "github://Marsupilami23/myesphometemplates/kauf-plf12-plug/standard/project.yaml@main"
  import_full_config: false
  
# https://esphome.io/guides/automations.html#global-variables
globals:
  - id: global_forced_addr
    type: int
    restore_value: no
    initial_value: '12345'
  - id: global_quick_boot_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: global_has_debounce
    type: boolean
    restore_value: no
    initial_value: "false"

# https://esphome.io/components/esphome.html#adjusting-flash-writes
preferences:
  # setting interval to 5 minutes since this defines writing total daily energy to flash, which will occur
  # every interval length 24/7/365.  Created a specific save script that is executed for things that need
  # to save more quickly.
  flash_write_interval: 5min

# https://esphome.io/components/esphome.html
esphome:
  name: "${device_code}"
  friendly_name: "${device_name}"
  comment: "${device_model} bulb by ${device_make}"
  name_add_mac_suffix: false
  min_version: "2024.11.0"
  project:
    name: "${device_make}.${device_model}"
    version: "${package_version}"
  on_boot:
    then:
        # set default values for template sensors, otherwise they are unknown.
      - script.execute: script_set_power_leds
      - script.execute: on_wifi_connect
