substitutions:
  # WIFI Substitutions
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password
  disable_webserver: "false"

# Allow importing of this package
dashboard_import:
  package_import_url: "github://Marsupilami23/myesphometemplates/kauf-plf12-plug/standard/wifi.yaml@main"
  import_full_config: false

# Enable Home Assistant API
api:
  id: dogain_api
  reboot_timeout: "${sub_api_reboot_timeout}"
  encryption:
    key: "${api_key}"

sensor:
  - platform: wifi_signal
    name: "RSSI"
    id: sensor_rssi
    update_interval: 60s
    entity_category: "diagnostic"

# Enable OTA
ota:
  - platform: esphome
    id: my_ota
    password: "${ota_password}"
    on_error:
      then:
        - button.press: restart_button
safe_mode:
  num_attempts: "${sub_ota_num_attempts}"
  
# Enable WIFI and AP for capitve portal
wifi:
  fast_connect: false
  power_save_mode: none
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  ap:
    ssid: "${device_code}-setup"
    password: "${wifi_password}"
  forced_addr: 8
  global_addr: global_forced_addr

web_server:
  disable: "${disable_webserver}"
  version: 3
  js_url: https//kaufha.com/v2/www.js

captive_portal:
