# NOTE: This file is not a stand-alone package. It is part of
# a 'root' device template and expects the substitutions that
# are hereby referenced to be defined by its parent.

substitutions:
  # WiFi Substitutions
  api_key: !secret api_key_shelly_dimmer2
  api_key: !secret api_key_hallway_light
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password

# Enable Home Assistant API
api:
  encryption:
    key: "${api_key}"

sensor:
  - platform: wifi_signal
    name: "RSSI"
    id: sensor_rssi
    update_interval: 60s
    entity_category: "diagnostic"

# Enable OTA
ota:
  - platform: esphome
#    safe_mode: true
    password: "${ota_password}"
		num_attempts: $sub_ota_num_attempts
  on_error:
    then:
      - button.press: restart_button

# Enable WiFi and AP for captive portal
wifi:
  fast_connect: false
  power_save_mode: none
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  use_address: "${device_ip}"
	ap:
    ap_timeout: $wifi_ap_timeout

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # password for hostspot is the same as password for net AP (needs captive_portal)
  ap:
    ssid: "${device_code}-setup"
    password: "${wifi_password}"

captive_portal:
