# NOTE: This file is not a stand-alone package. It is part of
# a 'root' device template and expects the substitutions that
# are hereby referenced to be defined by its parent.

binary_sensor:
  - platform: gpio
    pin: GPIO5
    id: light_0_touch
    name: "I - Dimming Control"
    internal: false
    on_multi_click:
    - timing:
        - ON for at most ${timing_press_threshold}
      then:
        - script.execute: script_dimmer_toggle
    - timing:
        - ON for at least ${timing_press_threshold}
      then:
        - script.execute: script_start_dimming_up
    on_release:
      then:
        - script.execute: script_stop_dimming