button:
  - platform: restart
    id: restart_button
    name: "${device_name} Restart Firmware"
    entity_category: diagnostic
    disabled_by_default: $disable_entities

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${device_name} IP Address"
      entity_category: diagnostic
      disabled_by_default: "${disable_entities}"

  - platform: template
    id: update_time
    name: "Current Time"
    lambda: |-
      char str[17];
      time_t currTime = id(homeassistant_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M", localtime(&currTime));
      return { str };
    icon: "mdi:clock"

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

degug:
  update_intervals: 10s

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    fragmentation:
      name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"

logger:
  level: debug
