substitutions:
  # Generated name and unique device id for the device
  # Not intended for user substitutions
  device_name: "${device_location_name} ${device_type_name}"
  device_code: "${device_location_code}-${device_type_code}"
  device_model: "Door Sensor"
  device_make: "XFOX"
  package_version: "2024.11.20"

# Allow importing this package
dashboard_import:
  package_import_url: "github://Marsupilami23/myesphometemplates/dogain-rgbww-bulbs-bk72xx/standard/project.yaml@main"
  import_full_config: false
  
# https://esphome.io/components/esphome.html
esphome:
  name: "${device_code}"
  friendly_name: "${device_name}"
  comment: "${device_model} by ${device_make}"
  name_add_mac_suffix: false
  min_version: "2024.11.0"
  project:
    name: "${device_make}.${device_model}"
    version: "${package_version}"
  on_boot:
    # https://esphome.io/components/esphome.html#on-boot
    - priority: 600.0 # 600.0: This is where most sensors are set up.
      then:
        - component.update: VCC
        - switch.turn_on: batt_dv # start measuring voltage
    - priority: 100.0
      then:
        - output.turn_on: activity_led_output
    - priority: -100 # 200.0: Network connections like MQTT/native API are set up at this priority.
      then:
        - component.update: VCC
        - component.update: homeassistant_time
        - component.update: update_time
        - script.execute: script_deep_sleep

globals:
  - id: first_connect_ms_int
    type: uint32_t
    initial_value: '0'
